# Example 1: RandomUser API

In [1]:
!pip install randomuser
!pip install pandas

Requirement already satisfied: randomuser in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (1.6)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [2]:
from randomuser import RandomUser
import pandas as pd

In [3]:
r = RandomUser()
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x204e43a1fd0>,
 <randomuser.RandomUser at 0x204e43a2010>,
 <randomuser.RandomUser at 0x204e43a2050>,
 <randomuser.RandomUser at 0x204e43a2090>,
 <randomuser.RandomUser at 0x204e43a20d0>,
 <randomuser.RandomUser at 0x204e43a2150>,
 <randomuser.RandomUser at 0x204e43a2190>,
 <randomuser.RandomUser at 0x204e43a21d0>,
 <randomuser.RandomUser at 0x204e43a2210>,
 <randomuser.RandomUser at 0x204e43a2110>]

In [4]:
for user in some_list:
    print (user.get_full_name(), user.get_email(), user.get_username())

Jur Hiwat jur.hiwat@example.com ticklishzebra641
Mervyn Alblas mervyn.alblas@example.com tinycat757
Maria Morris maria.morris@example.com beautifulwolf873
Phoebe Foster phoebe.foster@example.com lazydog805
Yvonne Bunk yvonne.bunk@example.com tinypeacock133
Niki Mijnders niki.mijnders@example.com tinyzebra922
Jaxon Turner jaxon.turner@example.com lazysnake392
سهیل سالاری shyl.slry@example.com angrybutterfly172
Lesley Kokx lesley.kokx@example.com bigladybug362
Andrés Cavalcanti andres.cavalcanti@example.com smallsnake289

In [5]:
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/55.jpg
https://randomuser.me/api/portraits/men/16.jpg
https://randomuser.me/api/portraits/women/24.jpg
https://randomuser.me/api/portraits/women/17.jpg
https://randomuser.me/api/portraits/women/3.jpg
https://randomuser.me/api/portraits/women/73.jpg
https://randomuser.me/api/portraits/men/54.jpg
https://randomuser.me/api/portraits/men/52.jpg
https://randomuser.me/api/portraits/men/82.jpg
https://randomuser.me/api/portraits/men/25.jpg

We can build a table as a Pandas DataFrame containing some parameters corresponding to each user

In [6]:
def get_users(number_of_users):
    # input: number of users to generate (number of rows in DataFrame)
    # output: Pandas DataFrame with users information
    users = []   # list to fill with user dictionaries
    for user in RandomUser.generate_users(number_of_users):
        users.append({"Name":user.get_full_name(), "Gender":user.get_gender(), "City":user.get_city(), "Email":user.get_email(), "Username":user.get_username(), "Picture":user.get_picture()})
    return pd.DataFrame(users)

In [7]:
get_users(10)

,Name,Gender,City,Email,Username,Picture
0,Avery Anderson,female,Dorchester,avery.anderson@example.com,whiterabbit278,https://randomuser.me/api/portraits/women/81.jpg
1,Nalan Baykam,female,Sinop,nalan.baykam@example.com,greenbird974,https://randomuser.me/api/portraits/women/2.jpg
2,Eelis Ruona,male,Kärkölä,eelis.ruona@example.com,blueladybug727,https://randomuser.me/api/portraits/men/14.jpg
3,Marie Dekens,female,Stuifzand gem M-Drenthe,marie.dekens@example.com,bigsnake359,https://randomuser.me/api/portraits/women/96.jpg
4,Pia Deschamps,female,Miège,pia.deschamps@example.com,sadcat224,https://randomuser.me/api/portraits/women/3.jpg
5,Dalya Stempher,female,Sintjohannesga,dalya.stempher@example.com,silverbear414,https://randomuser.me/api/portraits/women/76.jpg
6,Monica Perkins,female,Gladstone,monica.perkins@example.com,crazygorilla915,https://randomuser.me/api/portraits/women/19.jpg
7,Jordan Patel,male,Christchurch,jordan.patel@example.com,ticklishzebra899,https://randomuser.me/api/portraits/men/88.jpg
8,Léonard Leclerc,male,Rennes,leonard.leclerc@example.com,lazybutterfly427,https://randomuser.me/api/portraits/men/99.jpg
9,Santana Aragão,male,Porto Alegre,santana.aragao@example.com,yellowswan666,https://randomuser.me/api/portraits/men/21.jpg

# Example 2: Fruityvice API

In [8]:
import requests
import json

Instead of downloading the API, we use it via HTTP requests, a more common approach.

In [9]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")

Convert fetched result to text, and then to JSON

In [10]:
results = json.loads(data.text)
results

[{'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 81,
   'fat': 0.0,
   'sugar': 18.0,
   'carbohydrates': 18.0,
   'protein': 0.0}},
 {'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.8}},
 {'name': 'Banana',
  'id': 1,
  'family': 'Musaceae',
  'order': 'Zingiberales',
  'genus': 'Musa',
  'nutritions': {'calories': 96,
   'fat': 0.2,
   'sugar': 17.2,
   'carbohydrates': 22.0,
   'protein': 1.0}},
 {'name': 'Tomato',
  'id': 5,
  'family': 'Solanaceae',
  'order': 'Solanales',
  'genus': 'Solanum',
  'nutritions': {'calories': 74,
   'fat': 0.2,
   'sugar': 2.6,
   'carbohydrates': 3.9,
   'protein': 0.9}},
 {'name': 'Pear',
  'id': 4,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Pyrus',
  'nutritions': {'calories': 57,
   'fat': 0.1,
   'sugar': 10.0,
   'carbohydrates': 15.0,
   'protein': 0.4}},
 {'name': 'Durian',
  'id': 60,
  'family': 'Malvaceae',
  'order': 'Malvales',
  'genus': 'Durio',
  'nutritions': {'calories': 147,
   'fat': 5.3,
   'sugar': 6.75,
   'carbohydrates': 27.1,
   'protein': 1.5}},
 {'name': 'Blackberry',
  'id': 64,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 40,
   'fat': 0.4,
   'sugar': 4.5,
   'carbohydrates': 9.0,
   'protein': 1.3}},
 {'name': 'Lingonberry',
  'id': 65,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 50,
   'fat': 0.34,
   'sugar': 5.74,
   'carbohydrates': 11.3,
   'protein': 0.75}},
 {'name': 'Kiwi',
  'id': 66,
  'family': 'Actinidiaceae',
  'order': 'Struthioniformes',
  'genus': 'Apteryx',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 9.0,
   'carbohydrates': 15.0,
   'protein': 1.1}},
 {'name': 'Lychee',
  'id': 67,
  'family': 'Sapindaceae',
  'order': 'Sapindales',
  'genus': 'Litchi',
  'nutritions': {'calories': 66,
   'fat': 0.44,
   'sugar': 15.0,
   'carbohydrates': 17.0,
   'protein': 0.8}},
 {'name': 'Pineapple',
  'id': 10,
  'family': 'Bromeliaceae',
  'order': 'Poales',
  'genus': 'Ananas',
  'nutritions': {'calories': 50,
   'fat': 0.12,
   'sugar': 9.85,
   'carbohydrates': 13.12,
   'protein': 0.54}},
 {'name': 'Fig',
  'id': 68,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Ficus',
  'nutritions': {'calories': 74,
   'fat': 0.3,
   'sugar': 16.0,
   'carbohydrates': 19.0,
   'protein': 0.8}},
 {'name': 'Gooseberry',
  'id': 69,
  'family': 'Grossulariaceae',
  'order': 'Saxifragales',
  'genus': 'Ribes',
  'nutritions': {'calories': 44,
   'fat': 0.6,
   'sugar': 0.0,
   'carbohydrates': 10.0,
   'protein': 0.9}},
 {'name': 'Passionfruit',
  'id': 70,
  'family': 'Passifloraceae',
  'order': 'Malpighiales',
  'genus': 'Passiflora',
  'nutritions': {'calories': 97,
   'fat': 0.7,
   'sugar': 11.2,
   'carbohydrates': 22.4,
   'protein': 2.2}},
 {'name': 'Plum',
  'id': 71,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 46,
   'fat': 0.28,
   'sugar': 9.92,
   'carbohydrates': 11.4,
   'protein': 0.7}},
 {'name': 'Orange',
  'id': 2,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 43,
   'fat': 0.2,
   'sugar': 8.2,
   'carbohydrates': 8.3,
   'protein': 1.0}},
 {'name': 'GreenApple',
  'id': 72,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 21,
   'fat': 0.1,
   'sugar': 6.4,
   'carbohydrates': 3.1,
   'protein': 0.4}},
 {'name': 'Raspberry',
  'id': 23,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 53,
   'fat': 0.7,
   'sugar': 4.4,
   'carbohydrates': 12.0,
   'protein': 1.2}},
 {'name': 'Watermelon',
  'id': 25,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Citrullus',
  'nutritions': {'calories': 30,
   'fat': 0.2,
   'sugar': 6.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Lemon',
  'id': 26,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 29,
   'fat': 0.3,
   'sugar': 2.5,
   'carbohydrates': 9.0,
   'protein': 1.1}},
 {'name': 'Mango',
  'id': 27,
  'family': 'Anacardiaceae',
  'order': 'Sapindales',
  'genus': 'Mangifera',
  'nutritions': {'calories': 60,
   'fat': 0.38,
   'sugar': 13.7,
   'carbohydrates': 15.0,
   'protein': 0.82}},
 {'name': 'Blueberry',
  'id': 33,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.0}},
 {'name': 'Apple',
  'id': 6,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 52,
   'fat': 0.4,
   'sugar': 10.3,
   'carbohydrates': 11.4,
   'protein': 0.3}},
 {'name': 'Guava',
  'id': 37,
  'family': 'Myrtaceae',
  'order': 'Myrtales',
  'genus': 'Psidium',
  'nutritions': {'calories': 68,
   'fat': 1.0,
   'sugar': 9.0,
   'carbohydrates': 14.0,
   'protein': 2.6}},
 {'name': 'Apricot',
  'id': 35,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 15,
   'fat': 0.1,
   'sugar': 3.2,
   'carbohydrates': 3.9,
   'protein': 0.5}},
 {'name': 'Melon',
  'id': 41,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitaceae',
  'genus': 'Cucumis',
  'nutritions': {'calories': 34,
   'fat': 0.0,
   'sugar': 8.0,
   'carbohydrates': 8.0,
   'protein': 0.0}},
 {'name': 'Tangerine',
  'id': 77,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 45,
   'fat': 0.4,
   'sugar': 9.1,
   'carbohydrates': 8.3,
   'protein': 0.0}},
 {'name': 'Pitahaya',
  'id': 78,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Cactaceae',
  'nutritions': {'calories': 36,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 7.0,
   'protein': 1.0}},
 {'name': 'Lime',
  'id': 44,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 25,
   'fat': 0.1,
   'sugar': 1.7,
   'carbohydrates': 8.4,
   'protein': 0.3}},
 {'name': 'Pomegranate',
  'id': 79,
  'family': 'Lythraceae',
  'order': 'Myrtales',
  'genus': 'Punica',
  'nutritions': {'calories': 83,
   'fat': 1.2,
   'sugar': 13.7,
   'carbohydrates': 18.7,
   'protein': 1.7}},
 {'name': 'Dragonfruit',
  'id': 80,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Selenicereus',
  'nutritions': {'calories': 60,
   'fat': 1.5,
   'sugar': 8.0,
   'carbohydrates': 9.0,
   'protein': 9.0}},
 {'name': 'Grape',
  'id': 81,
  'family': 'Vitaceae',
  'order': 'Vitales',
  'genus': 'Vitis',
  'nutritions': {'calories': 69,
   'fat': 0.16,
   'sugar': 16.0,
   'carbohydrates': 18.1,
   'protein': 0.72}},
 {'name': 'Morus',
  'id': 82,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Morus',
  'nutritions': {'calories': 43,
   'fat': 0.39,
   'sugar': 8.1,
   'carbohydrates': 9.8,
   'protein': 1.44}},
 {'name': 'Feijoa',
  'id': 76,
  'family': 'Myrtaceae',
  'order': 'Myrtoideae',
  'genus': 'Sellowiana',
  'nutritions': {'calories': 44,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Avocado',
  'id': 84,
  'family': 'Lauraceae',
  'order': 'Laurales',
  'genus': 'Persea',
  'nutritions': {'calories': 160,
   'fat': 14.66,
   'sugar': 0.66,
   'carbohydrates': 8.53,
   'protein': 2.0}},
 {'name': 'Kiwifruit',
  'id': 85,
  'family': 'Actinidiaceae',
  'order': 'Ericales',
  'genus': 'Actinidia',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 8.9,
   'carbohydrates': 14.6,
   'protein': 1.14}},
 {'name': 'Cranberry',
  'id': 87,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 46,
   'fat': 0.1,
   'sugar': 4.0,
   'carbohydrates': 12.2,
   'protein': 0.4}},
 {'name': 'Cherry',
  'id': 9,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 50,
   'fat': 0.3,
   'sugar': 8.0,
   'carbohydrates': 12.0,
   'protein': 1.0}},
 {'name': 'Peach',
  'id': 86,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 39,
   'fat': 0.25,
   'sugar': 8.4,
   'carbohydrates': 9.5,
   'protein': 0.9}},
 {'name': 'Jackfruit',
  'id': 94,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Artocarpus',
  'nutritions': {'calories': 95,
   'fat': 0.0,
   'sugar': 19.1,
   'carbohydrates': 23.2,
   'protein': 1.72}},
 {'name': 'Horned Melon',
  'id': 95,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucumis',
  'nutritions': {'calories': 44,
   'fat': 1.26,
   'sugar': 0.5,
   'carbohydrates': 7.56,
   'protein': 1.78}},
 {'name': 'Hazelnut',
  'id': 96,
  'family': 'Betulaceae',
  'order': 'Fagales',
  'genus': 'Corylus',
  'nutritions': {'calories': 628,
   'fat': 61.0,
   'sugar': 4.3,
   'carbohydrates': 17.0,
   'protein': 15.0}},
 {'name': 'Pomelo',
  'id': 98,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 37,
   'fat': 0.0,
   'sugar': 8.5,
   'carbohydrates': 9.67,
   'protein': 0.82}},
 {'name': 'Mangosteen',
  'id': 99,
  'family': 'Clusiaceae',
  'order': 'Malpighiales',
  'genus': 'Garcinia',
  'nutritions': {'calories': 73,
   'fat': 0.58,
   'sugar': 16.11,
   'carbohydrates': 17.91,
   'protein': 0.41}},
 {'name': 'Pumpkin',
  'id': 100,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucurbita',
  'nutritions': {'calories': 25,
   'fat': 0.3,
   'sugar': 3.3,
   'carbohydrates': 4.6,
   'protein': 1.1}},
 {'name': 'Japanese Persimmon',
  'id': 101,
  'family': ' Ebenaceae',
  'order': ' Ericales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 70,
   'fat': 0.2,
   'sugar': 13.0,
   'carbohydrates': 19.0,
   'protein': 0.6}},
 {'name': 'Papaya',
  'id': 42,
  'family': 'Caricaceae',
  'order': 'Brassicales',
  'genus': 'Carica',
  'nutritions': {'calories': 39,
   'fat': 0.3,
   'sugar': 4.4,
   'carbohydrates': 5.8,
   'protein': 0.5}},
 {'name': 'Annona',
  'id': 103,
  'family': 'Annonaceae',
  'order': 'Rosales',
  'genus': 'Annonas',
  'nutritions': {'calories': 92,
   'fat': 0.29,
   'sugar': 3.4,
   'carbohydrates': 19.1,
   'protein': 1.5}},
 {'name': 'Ceylon Gooseberry',
  'id': 104,
  'family': 'Salicaceae',
  'order': 'Malpighiales',
  'genus': 'Dovyalis',
  'nutritions': {'calories': 47,
   'fat': 0.3,
   'sugar': 8.1,
   'carbohydrates': 9.6,
   'protein': 1.2}}]

In [11]:
pd.DataFrame(results).head()

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."

The "nutritions" column contains nested dictionaries. We should flatten/normalize it

In [12]:
df2 = pd.json_normalize(results)
df2.head()

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.0,18.0,18.0,0.0
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.4,5.4,5.5,0.8
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.2,2.6,3.9,0.9
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.1,10.0,15.0,0.4

Now we can work with the DataFrame as usual. For example, we can access family, genus and calories for the banana entry:

In [13]:
banana = df2.loc[df2["name"] == 'Banana']   # get the banana row
(banana.iloc[0]['family']) , (banana.iloc[0]['genus']), (banana.iloc[0]['nutritions.calories'])

('Musaceae', 'Musa', np.int64(96))

# Example 3: Official Joke API

In [14]:
# url that returns 10 random jokes
url = 'https://official-joke-api.appspot.com/jokes/ten'

joke_response = requests.get(url)

In [15]:
# convert to text, then to JSON, then to DataFrame
joke_df = pd.DataFrame(json.loads(joke_response.text))
joke_df

,type,setup,punchline,id
0,general,How many apples grow on a tree?,All of them!,137
1,programming,Which song would an exception sing?,Can't catch me - Avicii,32
2,general,What do ghosts call their true love?,Their ghoul-friend,102
3,programming,What's the best thing about a Boolean?,"Even if you're wrong, you're only off by a bit.",409
4,general,Did you watch the new comic book movie?,It was very graphic!,66
5,general,How many bones are in the human hand?,A handful of them.,138
6,programming,Why do programmers prefer dark chocolate?,Because it's bitter like their code.,416
7,general,Why did the cookie cry?,It was feeling crumby.,321
8,general,What do you call a monkey in a mine field?,A babooooom!,210
9,general,What do you get when you cross a snowman with ...,Frostbite.,232

In [16]:
# Extract only the setup and punchline columns
jokes = joke_df[['setup', 'punchline']]
jokes

,setup,punchline
0,How many apples grow on a tree?,All of them!
1,Which song would an exception sing?,Can't catch me - Avicii
2,What do ghosts call their true love?,Their ghoul-friend
3,What's the best thing about a Boolean?,"Even if you're wrong, you're only off by a bit."
4,Did you watch the new comic book movie?,It was very graphic!
5,How many bones are in the human hand?,A handful of them.
6,Why do programmers prefer dark chocolate?,Because it's bitter like their code.
7,Why did the cookie cry?,It was feeling crumby.
8,What do you call a monkey in a mine field?,A babooooom!
9,What do you get when you cross a snowman with ...,Frostbite.